/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "ui.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0              (GUI_ID_USER + 0x00)
#define ID_BUTTON_2ABC              (GUI_ID_USER + 0x01)
#define ID_BUTTON_3DEF              (GUI_ID_USER + 0x02)
#define ID_BUTTON_1PUN              (GUI_ID_USER + 0x03)
#define ID_BUTTON_DEL              (GUI_ID_USER + 0x04)
#define ID_BUTTON_INPUT              (GUI_ID_USER + 0x05)
#define ID_BUTTON_4GHI              (GUI_ID_USER + 0x06)
#define ID_BUTTON_5JKL              (GUI_ID_USER + 0x07)
#define ID_BUTTON_6MNO              (GUI_ID_USER + 0x08)
#define ID_BUTTON_7PQRS              (GUI_ID_USER + 0x09)
#define ID_BUTTON_8TUV              (GUI_ID_USER + 0x0A)
#define ID_BUTTON_9WXYZ             (GUI_ID_USER + 0x0B)
#define ID_BUTTON_SPACE             (GUI_ID_USER + 0x0C)
#define ID_BUTTON_0             (GUI_ID_USER + 0x0D)
#define ID_BUTTON_OK             (GUI_ID_USER + 0x0E)
#define ID_BUTTON_CLEAR             (GUI_ID_USER + 0x0F)
#define ID_BUTTON_BACK             (GUI_ID_USER + 0x10)
#define ID_BUTTON_R0             (GUI_ID_USER + 0x11)
#define ID_BUTTON_L0             (GUI_ID_USER + 0x12)
#define ID_BUTTON_R1             (GUI_ID_USER + 0x13)
#define ID_BUTTON_L1             (GUI_ID_USER + 0x14)

#define ID_TEXT_S0             (GUI_ID_USER + 0x15)
#define ID_TEXT_S1             (GUI_ID_USER + 0x16)
#define ID_TEXT_S2             (GUI_ID_USER + 0x17)
#define ID_TEXT_C0             (GUI_ID_USER + 0x18)
#define ID_TEXT_C1             (GUI_ID_USER + 0x19)
#define ID_TEXT_C2             (GUI_ID_USER + 0x1A)
#define ID_TEXT_C3             (GUI_ID_USER + 0x1B)
#define ID_TEXT_C4             (GUI_ID_USER + 0x1C)
#define ID_TEXT_C5             (GUI_ID_USER + 0x1D)

#define ID_EDIT_0             (GUI_ID_USER + 0x1E)


// USER START (Optionally insert additional defines)

void(*ButtonKeyCB)(char *a,uint8_t cmd);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 200, 207, 0, 0x0, 0 },
  //line 4
  { BUTTON_CreateIndirect, "2ABC", ID_BUTTON_2ABC, 55, 90, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3DEF", ID_BUTTON_3DEF, 105, 90, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1,.?!", ID_BUTTON_1PUN, 5, 90, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DEL", ID_BUTTON_DEL, 155, 90, 40, 20, 0, 0x0, 0 },
  //line 5
  { BUTTON_CreateIndirect, "4GHI", ID_BUTTON_4GHI, 5, 120, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5JKL", ID_BUTTON_5JKL, 55, 120, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6MNO", ID_BUTTON_6MNO, 105, 120, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CLEAR", ID_BUTTON_CLEAR, 155, 120, 40, 20, 0, 0x0, 0 },
  //line 6
  { BUTTON_CreateIndirect, "7PQRS", ID_BUTTON_7PQRS, 5, 150, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8TUV", ID_BUTTON_8TUV, 55, 150, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9WXYZ", ID_BUTTON_9WXYZ, 105, 150, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_OK, 155, 150, 40, 20, 0, 0x0, 0 },
  //line 7
  { BUTTON_CreateIndirect, "BACK", ID_BUTTON_BACK, 5, 180, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_0, 55, 180, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SPACE", ID_BUTTON_SPACE, 105, 180, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "INPUT", ID_BUTTON_INPUT, 155, 180, 40, 20, 0, 0x0, 0 },
  //line 3
  { BUTTON_CreateIndirect, "L0", ID_BUTTON_L0, 3, 60, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "S0", ID_TEXT_S0, 33, 60, 40, 20, 0, 8, 0 },
  { TEXT_CreateIndirect, "S1", ID_TEXT_S1, 81, 60, 40, 20, 0, 8, 0 },
  { TEXT_CreateIndirect, "S2", ID_TEXT_S2, 129, 60, 40, 20, 0, 8, 0 },
  { BUTTON_CreateIndirect, "R0", ID_BUTTON_R0, 177, 60, 20, 20, 0, 0x0, 0 },
  //line 2
  { BUTTON_CreateIndirect, "L1", ID_BUTTON_L1, 3, 30, 20, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "C0", ID_TEXT_C0, 25, 30, 20, 20, 0, 5, 0 },
  { TEXT_CreateIndirect, "C1", ID_TEXT_C1, 50, 30, 20, 20, 0, 5, 0 },
  { TEXT_CreateIndirect, "C2", ID_TEXT_C2, 75, 30, 20, 20, 0, 5, 0 },
  { TEXT_CreateIndirect, "C3", ID_TEXT_C3, 100, 30, 20, 20, 0, 5, 0 },
  { TEXT_CreateIndirect, "C4", ID_TEXT_C4, 125, 30, 20, 20, 0, 5, 0 },
  { TEXT_CreateIndirect, "C5", ID_TEXT_C5, 150, 30, 20, 20, 0, 5, 0 },
  { BUTTON_CreateIndirect, "R1", ID_BUTTON_R1, 177, 30, 20, 20, 0, 0x0, 0 },
  //line 1
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 5, 3, 190, 20, 0, 50, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*
*
**********************************************************************
*/


typedef struct{
int id;
uint8_t num;//
}_BUTTON;

_BUTTON button[]={
{ID_BUTTON_1PUN,5},
{ID_BUTTON_2ABC,4},
{ID_BUTTON_3DEF,4},
{ID_BUTTON_4GHI,4},
{ID_BUTTON_5JKL,4},
{ID_BUTTON_6MNO,4},
{ID_BUTTON_7PQRS,5},
{ID_BUTTON_8TUV,4},
{ID_BUTTON_9WXYZ,5},
};
typedef struct{
uint8_t input;/*0:123 1:abc 2:ABC 3:pun*/
uint8_t pun;/*0 1 2*/
uint8_t button_id;/**/
char **in;
}_INPUT;
static _INPUT input={0,0,0,0};//0:123 1:abc 2:ABC 3:pinyin
static char edit[50];
static WM_HWIN hItemEdit;
//static WM_HTIMER hTimer;

static WM_HWIN hItemTextS[3];

static WM_HWIN hItemTextC[6];
char *input123[]={
"1","2","3","4","5","6","7","8","9"
};
char *inputabc[]={
",.?!","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"
};
char *inputABC[]={
",.?!","ABC","DEF","GHI","JKL","MNO","PQRS","TUV","WXYZ"
};
char *inputPun0[]={
"[","]","{","}","#","%","^","*","+"
};
char *inputPun1[]={
"=","_","\\","/","|","~","<",">","-"
};
char *inputPun2[]={
":",";","(",")","$","&","'","",""
};

void InitKey(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;

    if(input.input==0)input.in = input123;
    else if(input.input==1)input.in = inputabc;
    else if(input.input==2)input.in = inputABC;
    else if(input.input==3)
    {
        if(input.pun==0)input.in = inputPun0;
        else if(input.pun==1)input.in = inputPun1;
        else if(input.pun==2)input.in = inputPun2;
        else
        {
            input.pun = 0;
            input.in = inputPun0;
        }
    }
    else
    {
        input.input = 0;
        input.in = input123;
    }

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1PUN);
    BUTTON_SetText(hItem, input.in[0]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2ABC);
    BUTTON_SetText(hItem, input.in[1]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3DEF);
    BUTTON_SetText(hItem, input.in[2]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4GHI);
    BUTTON_SetText(hItem, input.in[3]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5JKL);
    BUTTON_SetText(hItem, input.in[4]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6MNO);
    BUTTON_SetText(hItem, input.in[5]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7PQRS);
    BUTTON_SetText(hItem, input.in[6]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8TUV);
    BUTTON_SetText(hItem, input.in[7]);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9WXYZ);
    BUTTON_SetText(hItem, input.in[8]);
    if(input.input==0)
    {
      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_INPUT);
      BUTTON_SetText(hItem, "123");
    }
    else if(input.input==1)
    {
       hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_INPUT);
       BUTTON_SetText(hItem, "abc");
    }
    else if(input.input==2)
    {
       hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_INPUT);
       BUTTON_SetText(hItem, "ABC");
    }
    else if(input.input==3)
    {
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_INPUT);
        BUTTON_SetText(hItem, ",.?!");
    }
    EDIT_SetText(hItemEdit, "");
    EDIT_SetTextAlign(hItemEdit, GUI_TA_LEFT | GUI_TA_VCENTER);

}

void  InitKeyStatic(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    uint8_t i=0;
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DEL);
    BUTTON_SetText(hItem, "DEL");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SPACE);
    BUTTON_SetText(hItem, "SPACE");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "0");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_OK);
    BUTTON_SetText(hItem, "OK");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CLEAR);
    BUTTON_SetText(hItem, "C");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_BACK);
    BUTTON_SetText(hItem, "BACK");
    i=0;
    hItemTextS[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_S0);
    TEXT_SetTextAlign(hItemTextS[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextS[i], "");
    i++;
    hItemTextS[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_S1);
    TEXT_SetTextAlign(hItemTextS[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextS[i], "");
    i++;
    hItemTextS[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_S2);
    TEXT_SetTextAlign(hItemTextS[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextS[i], "");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R0);
    BUTTON_SetText(hItem, "->");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L0);
    BUTTON_SetText(hItem, "<-");
    i=0;
    hItemTextC[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C0);
    TEXT_SetTextAlign(hItemTextC[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextC[i], "");
    i++;
    hItemTextC[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C1);
    TEXT_SetTextAlign(hItemTextC[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextC[i], "");
    i++;
    hItemTextC[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C2);
    TEXT_SetTextAlign(hItemTextC[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextC[i], "");
    i++;
    hItemTextC[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C3);
    TEXT_SetTextAlign(hItemTextC[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextC[i], "");
    i++;
    hItemTextC[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C4);
    TEXT_SetTextAlign(hItemTextC[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextC[i], "");
    i++;
    hItemTextC[i] = WM_GetDialogItem(pMsg->hWin, ID_TEXT_C5);
    TEXT_SetTextAlign(hItemTextC[i], GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItemTextC[i], "");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R1);
    BUTTON_SetText(hItem, "->");
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L1);
    BUTTON_SetText(hItem, "<-");

}

void editCat(char *a)
{
//    EDIT_GetText(hItemEdit, edit,50);
//    strcat(edit,a);
//    EDIT_SetText(hItemEdit, edit);

    GUI_StoreKeyMsg(a[0], 1);
    GUI_StoreKeyMsg(a[0], 0);

}

void button1_9(WM_MESSAGE * pMsg,uint8_t i)
{
    int     NCode;
	  char str[4];
    uint8_t j=0;
    NCode = pMsg->Data.v;
    switch(NCode)
    {
        case WM_NOTIFICATION_RELEASED:
        if(input.input==0||input.input==3)
        {
           editCat(input.in[i]);
        }
        else if(input.input==1||input.input==2)
        {
            for(j=0;j<5;j++)
            {
                TEXT_SetText(hItemTextC[j],"");
            }
            for(j=0;j<button[i].num&&j<strlen(input.in[i]);j++)
            {
                str[0] = input.in[i][j];
                str[1]=0;
                TEXT_SetText(hItemTextC[j],str);
            }					
						sprintf(str,"%d",i+1);
            TEXT_SetText(hItemTextC[j++],str);
        }
        else
        {

        }
        break;
    }
}

void textC0_5(WM_MESSAGE * pMsg,uint8_t i)
{
    int     NCode;
	  char str[4];
    NCode = pMsg->Data.v;
    switch(NCode){
			case WM_NOTIFICATION_RELEASED:
        TEXT_GetText(hItemTextC[i],str,3);
        editCat(str);
    break;
    }
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
//  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  int     size;
  int     i=0;
  // USER ENDhItemTextC

  switch (pMsg->MsgId) {

  case WM_CREATE:

  break;
  case WM_INIT_DIALOG:
    hItemEdit = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    InitKeyStatic(pMsg);
    InitKey(pMsg);
    for(i=ID_BUTTON_2ABC; i<=ID_BUTTON_L1; i++) BUTTON_SetFocussable(WM_GetDialogItem(pMsg->hWin, i), 0);
		EDIT_SetFocussable(hItemEdit,0);
    //hTimer=WM_CreateTimer(pMsg->hWin,0,600,0);
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_1PUN:button1_9(pMsg,0);break;
    case ID_BUTTON_2ABC:button1_9(pMsg,1);break;
    case ID_BUTTON_3DEF:button1_9(pMsg,2);break;
    case ID_BUTTON_4GHI:button1_9(pMsg,3);break;
    case ID_BUTTON_5JKL:button1_9(pMsg,4);break;
    case ID_BUTTON_6MNO:button1_9(pMsg,5);break;
    case ID_BUTTON_7PQRS:button1_9(pMsg,6);break;
    case ID_BUTTON_8TUV:button1_9(pMsg,7);break;
    case ID_BUTTON_9WXYZ:button1_9(pMsg,8);break;

    case ID_TEXT_C0:textC0_5(pMsg,0);break;
    case ID_TEXT_C1:textC0_5(pMsg,1);break;
    case ID_TEXT_C2:textC0_5(pMsg,2);break;
    case ID_TEXT_C3:textC0_5(pMsg,3);break;
    case ID_TEXT_C4:textC0_5(pMsg,4);break;
    case ID_TEXT_C5:textC0_5(pMsg,5);break;

    case ID_BUTTON_0:
        switch(NCode) {
            case WM_NOTIFICATION_RELEASED:editCat("0");break;
        }
    break;
    case ID_BUTTON_SPACE:
        switch(NCode) {
            case WM_NOTIFICATION_RELEASED:editCat(" ");break;
        }
    break;

    case ID_BUTTON_DEL:
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

        EDIT_GetText(hItemEdit, edit,50);
        size = strlen(edit);
        if(size)size--;
        else {
            //ButtonKeyCB(edit,1);
            GUI_StoreKeyMsg(GUI_KEY_BACKSPACE, 1);
            GUI_StoreKeyMsg(GUI_KEY_BACKSPACE, 0);
        }
        edit[size]=0;
        EDIT_SetText(hItemEdit, edit);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
    break;
    case ID_BUTTON_CLEAR:
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        EDIT_GetText(hItemEdit, edit,50);
        size = strlen(edit);
   //     if(size==0)ButtonKeyCB(edit,2);
        edit[0]=0;
        EDIT_SetText(hItemEdit, edit);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
    break;

    case ID_BUTTON_L0:
        switch(NCode) {
            case WM_NOTIFICATION_RELEASED:
                if(input.input==3)
                {
                    input.pun = input.pun>0 ? input.pun-1:2;
                    InitKey(pMsg);
                }
            break;
        }
    break;

    case ID_BUTTON_R0:
        switch(NCode) {
            case WM_NOTIFICATION_RELEASED:
                if(input.input==3)
                {
                    input.pun = input.pun<2 ? input.pun+1:0;
                    InitKey(pMsg);
                }
            break;
        }
    break;

    case ID_BUTTON_INPUT:
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        input.input = input.input<3 ?  input.input+1 : 0;
        InitKey(pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
    break;

    case ID_BUTTON_BACK: // Notifications sent by 'L1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_HideWin(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
      case ID_BUTTON_OK:
        switch(NCode) {
           case WM_NOTIFICATION_RELEASED:

                EDIT_GetText(hItemEdit, edit,50);
                if(ButtonKeyCB!=NULL)
                {
                   ButtonKeyCB(edit,0);
                }
           break;
        }
      break;

    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

//WM_HWIN CreateKeyWindow(void);
WM_HWIN hKeyBoardWin;
WM_HWIN CreateKeyWindow() {

  hKeyBoardWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hKeyBoardWin;
}


//int showKeyBoard(void(*cb)(char *a,uint8_t cmd),int sizex,int sizey)
int showKeyBoard(int sizex,int sizey)
{
    if(sizex <200 || sizey <200)return -1;

  //  ButtonKeyCB = cb;

    WM_MoveTo(hKeyBoardWin,(sizex-200)/2,(sizey-200));
    WM_ShowWin(hKeyBoardWin);

    return 0;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
